// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ABK2WcjUyAht8p6ezrXuoIc5a6fCsTQ',
    appId: '1:828668442911:web:6dab7e35ccf7d94a78d82a',
    messagingSenderId: '828668442911',
    projectId: 'develop-f0ec3',
    authDomain: 'develop-f0ec3.firebaseapp.com',
    storageBucket: 'develop-f0ec3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfeqc0cUWNWwcfPkAeIjreq37cAsvBXO0',
    appId: '1:828668442911:android:adbf8f0dee4e6de678d82a',
    messagingSenderId: '828668442911',
    projectId: 'develop-f0ec3',
    storageBucket: 'develop-f0ec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5JgGVH7ICZndRo6KYEYshboQOe-qr8xo',
    appId: '1:828668442911:ios:dbade681e27ef0c978d82a',
    messagingSenderId: '828668442911',
    projectId: 'develop-f0ec3',
    storageBucket: 'develop-f0ec3.appspot.com',
    iosClientId: '828668442911-0m9cq6qpo855dj0hk9mrp87q7r5oha47.apps.googleusercontent.com',
    iosBundleId: 'com.example.developapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5JgGVH7ICZndRo6KYEYshboQOe-qr8xo',
    appId: '1:828668442911:ios:dbade681e27ef0c978d82a',
    messagingSenderId: '828668442911',
    projectId: 'develop-f0ec3',
    storageBucket: 'develop-f0ec3.appspot.com',
    iosClientId: '828668442911-0m9cq6qpo855dj0hk9mrp87q7r5oha47.apps.googleusercontent.com',
    iosBundleId: 'com.example.developapp',
  );
}
